### ISSUE TITLE
Pypi package

### ISSUE THREAD

**Issue by Dobatymo** [pablocael/pynear#20]
Since we are building wheels on CI already, it would be easy to upload them to PyPI automatically through Github actions as well. We need to agree on a name though. Should we use pyvptree (it's still available on PyPI https://pypi.org/project/pyvptree/) or use another name, maybe more generic related to nearest neighbor search?

**Comment by pablocael** [comment]
About the uploading to PyPI automatically, that would be very nice.
About the name, that is a good question and came in the right time because I was also thinking the same. I have plans to use different strategies of KNN search for binary indices. For me, the most important use case is binary indices and right now its very slow. Also, there is already a library called pyvptree which is not so well mantained and I prefer to keep away from this name because of that.
Im open to any name suggestion.

Can we maybe try to brainstorm some names in our side individually and decide or vote for one? Wdyt? Thank you.

**Comment by Dobatymo** [comment]
Fixed https://github.com/pablocael/pynear/pull/35
